### ISSUE TITLE
When using Litestar, errors within the admin app result in unexpected AttributeError's

### ISSUE THREAD

**Issue by Skelmis** [piccolo-orm/piccolo_admin#429]
TL:DR if using Litestar (any new version) within the admin panel, any exceptions raised also result in the following:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skelmis/.cache/pypoetry/virtualenvs/zero_website-Nzy3tQZa-py3.11/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skelmis/.cache/pypoetry/virtualenvs/zero_website-Nzy3tQZa-py3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skelmis/.cache/pypoetry/virtualenvs/zero_website-Nzy3tQZa-py3.11/lib/python3.11/site-packages/litestar/app.py", line 615, in __call__
    await self.asgi_handler(scope, receive, self._wrap_send(send=send, scope=scope))  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skelmis/.cache/pypoetry/virtualenvs/zero_website-Nzy3tQZa-py3.11/lib/python3.11/site-packages/litestar/middleware/_internal/exceptions/middleware.py", line 166, in __call__
    if litestar_app.logging_config and (logger := litestar_app.logger):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FastAPI' object has no attribute 'logging_config'
```

I'm just going to use this issue as a log of my dive into the what and the why

**Comment by Skelmis** [comment]
This appears to be because the litestar exception handling middleware expects `litestar_app = scope["app"]` which I think litestar implies is `type(scope['app']) == Litestar` but it's actually `type(scope['app']) == ASGIApp` which is just `ASGIApp: TypeAlias = Callable[[Scope, Receive, Send], Awaitable[None]]`.

This appears to be a Litestar issue so likely going to drop out of this issue and handle with them. Will update this issue with a resolution once applicable however

**Comment by sinisaos** [comment]
@Skelmis I can't reproduce your issue. In my case everything works in `Py3.11`, `Py3.12` and `Py3.13` with `Postgres`. With `SQlite` as in your [mcve](https://github.com/Skelmis/litestar-mcve) everything also works after I create tables and superuser with something like this

```python
from piccolo.apps.user.tables import BaseUser
from piccolo_api.session_auth.tables import SessionsBase

async def main():
    # Tables creating
    await BaseUser.create_table(if_not_exists=True)
    await SessionsBase.create_table(if_not_exists=True)
    await Task.create_table(if_not_exists=True)

    # Creating admin user
    if not await BaseUser.exists().where(BaseUser.email == "admin@test.com"):
        user = BaseUser(
            username="piccolo",
            password="piccolo123",
            email="admin@test.com",
            admin=True,
            active=True,
            superuser=True,
        )
        await user.save()

if __name__ == "__main__":
    asyncio.run(main())

    uvicorn.run("main:app", reload=True)
```

Sorry if I missed your point.

**Comment by Skelmis** [comment]
Yea, the [mcve](https://github.com/Skelmis/litestar-mcve) is 'as is' to provide a simple way to get the admin panel to error and induce the error from litestar (since the tables dont exist, it's guaranteed to error).

The error I was facing when I opened the issue originally was a fully configured environment with users, tables, etc. In said environment I was just inducing the errors via a different route.

---

The issue is less about the missing stuff, but instead about the fact that any exception thrown by the admin app results in `AttributeError` due to missing logging configs instead of the actual error.

I dived into it a bit in the [litestar discord](https://discord.com/channels/919193495116337154/1326018597134536735) and at least from my eyes its properly a litestar issue where the expectations of the framework don't meet what is supplied by Piccolo and is thus a litestar middleware issue.

**Comment by dantownsend** [comment]
Interesting - so the Litestar middleware expects a Litestar app and not a generic ASGI app. I think that's quite hard for us to fix on the Piccolo Admin side, but if you come up with any ideas let us know.

**Comment by Skelmis** [comment]
Agreed! I'm going to close this in favor of Litestar fixing it directly. I've opened an issue [here](https://github.com/litestar-org/litestar/issues/3934) for it.
